###
GET http://localhost:3000/api/v1/device

### GET DEVICE BY USERID
GET http://localhost:3000/api/v1/mydevice/65fa4a506c2997e0c03af63d
### GET DEVICE BY ID 
GET http://localhost:3000/api/v1/device/65fa41395c7050febf266843
###
POST http://localhost:3000/api/v1/device
Content-Type: application/json

{
    "name": "BP 2721 GM",
    "userId": "65fa4a506c2997e0c03af63d",
    "isLock": true
}
### EDIT DEVICE
PUT http://localhost:3000/device/657bcb2db4702828d9dd77f4
Content-Type: application/json

{
    "email": "yoga.pratama.pangest2u"
}
### DELETE DEVICE
DELETE http://localhost:3000/api/v1/device/65fa40ea6ee993de9bfbe138

### 
POST http://localhost:3000/api/v1/location 
Content-Type: application/json

{
    "deviceToken": "oU7lo1hq0YptJTEGOIC6dUc",
    "latitude": 1.06257,
    "longitude": 104.02858
}

###
GET http://localhost:3000/location/657bfc7686464d3bcab5bbc8
