###
GET http://localhost:3000/device

### GET DEVICE BY ID 
GET http://localhost:3000/device/65c198c707d3a8e9838cb649
###
POST http://localhost:3000/device
Content-Type: application/json

{
    "name": "Motor Teman",
    "userId": "65c1987907d3a8e9838cb648",
    "isLock": true
}
### EDIT DEVICE
PUT http://localhost:3000/device/657bcb2db4702828d9dd77f4
Content-Type: application/json

{
    "email": "yoga.pratama.pangest2u"
}
### DELETE DEVICE
DELETE http://localhost:3000/device/657bfc7686464d3bcab5bbc8

### 
POST http://localhost:3000/location 
Content-Type: application/json

{
    "deviceId": "657ffb6418c8219214e21588",
    "latitude": 104.10,
    "longitude": 4.10
}

###
GET http://localhost:3000/location/657bfc7686464d3bcab5bbc8
