### 
GET https://backend-tracker-app.vercel.app/user

### GET USER \
GET http://localhost:3000/api/v1/user
### GET USER BY ID 
GET http://localhost:3000/api/v1/user/65fa31ae6899d83985ddedcf

### REGISTER USER
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "email": "yoga.pratama.pangestu@gmail.com",
    "password": "yoga pratama"
}

### LOGIN USER
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "email": "yoga.pratama.pangestu@gmail.com",
    "password": "yoga pratama"
}

### LOGOUT USER
POST http://localhost:3000/api/v1/logout
Content-Type: application/json


### EDIT USER
PUT http://localhost:3000/user/657bcb2db4702828d9dd77f4
Content-Type: application/json

{
    "email": "yoga.pratama.pangest2u",
}
### DELETE USER
DELETE http://localhost:3000/user/657bfb73f75b89b7c4ba5f59